### ISSUE TITLE
Make the app Accessible.

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-mobile-app#19]
Will require research to see what exactly that means. Don't think Section 508 applies however what is an app reader and how does it read them.

**Comment by loganSims** [comment]
Since our iPhone app is a web app I'm going to try using the [WAI_ARIA](https://www.w3.org/WAI/intro/aria) standards to implement accessibility features in our app. GWT has a [short guide](http://www.gwtproject.org/doc/latest/DevGuideA11y.html) on how to implement ARIA features. Currently VoiceOver is working well with these features.

**Comment by loganSims** [comment]
Using this phonegap plug-in 
https://github.com/phonegap/phonegap-mobile-accessibility
